[package]
org = "ballerina"
name = "websub_tests"
version = "@toml.version@"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "../native/build/libs/websub-native-@project.version@.jar"
