[package]
org = "ballerina"
name = "websub"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["websub", "subscriber", "service", "listener"]
repository = "https://github.com/ballerina-platform/module-ballerina-websub"
license = ["Apache-2.0"]
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/websub-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "./lib/http-native-@http.native.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http2-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/commons-pool-@wso2commonspool.version@.jar"

[[platform.java11.dependency]]
path = "./lib/snakeyaml-@wso2snakeyaml.version@.jar"

[[platform.java11.dependency]]
path = "./lib/bcprov-jdk15on-@bouncycastle.version@.jar"

[[platform.java11.dependency]]
path = "./lib/bcpkix-jdk15on-@bouncycastle.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-@nettytcnative.version@.jar"

[[platform.java11.dependency]]
path = "./lib/org.wso2.carbon.metrics.core-@wso2carbonmetrics.version@.jar"
