[package]
org = "ballerina"
name = "websub"
version = "2.0.0"
distribution = "slbeta3"

[[platform.java11.dependency]]
path = "../native/build/libs/websub-native-2.0.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "./lib/http-native-2.0.0-20211007-231200-c19485f.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http2-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/commons-pool-1.5.6.wso2v1.jar"

[[platform.java11.dependency]]
path = "./lib/snakeyaml-1.26.0.wso2v1.jar"

[[platform.java11.dependency]]
path = "./lib/bcprov-jdk15on-1.69.jar"

[[platform.java11.dependency]]
path = "./lib/bcpkix-jdk15on-1.69.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.43.Final.jar"

[[platform.java11.dependency]]
path = "./lib/org.wso2.carbon.metrics.core-2.3.7.jar"
