[package]
org = "ballerina"
name = "websub"
version = "2.2.0"
authors = ["Ballerina"]
keywords = ["websub", "subscriber", "service", "listener"]
repository = "https://github.com/ballerina-platform/module-ballerina-websub"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "../native/build/libs/websub-native-2.2.0-SNAPSHOT.jar"
