[plugin]
id = "websub-compiler-plugin"
class = "io.ballerina.stdlib.websub.WebSubCompilerPlugin"

[[dependency]]
path = "../websub-compiler-plugin/build/libs/websub-compiler-plugin-@project.version@.jar"